raytune:
  log_dir: 
  num_cpus: 64
  num_gpus: 4
  num_samples: 10
  num_concurrent_trials: 10
  reuse_actors: true
  max_t: 40
  grace_period: 5
  num_to_keep: 10
  metric: val/val_loss
  search_alg: OptunaSearch
  concurrent_trials: 4
  num_workers: 1
  cpus_per_worker: 7
  gpus_per_worker: 0.25


  params_to_tune:
    # model.init_args.img_size: [64, 96, 128, 160, 192]
    # model.init_args.in_channels: [1, 3, 4]
    # model.init_args.patch_size: [8, 16, 24, 32]
    # model.init_args.emb_dim: [256, 384, 512, 640, 768]
    # model.init_args.num_layers: [4, 6, 8, 10, 12]
    # model.init_args.num_heads: [4, 6, 8, 10, 12]
    model.init_args.batch_size:
      type: choice
      values: [8, 16, 32, 64]

trainer:
  max_epochs: 10
  precision: 16-mixed
  gradient_clip_val: 1.0
  strategy: ray_ddp
  plugins: [ray_lightning_environment]
  enable_progress_bar: false
  default_root_dir: ./

model:
  class_path: models.vit_lightning.vit_lightning.ViTLightning
  init_args:
    img_size: 128
    in_channels: 3
    patch_size: 16
    emb_dim: 512
    num_layers: 8
    num_heads: 8
    mlp_ratio: 4.0
    dropout: 0.1
    learning_rate: 1e-3
    batch_size: 32
    num_workers: 4
    data_dir: ${oc.env:DATA_DIR}